eureka:
  client:
    service-url:
      defaultZone:  http://localhost:9090/eureka
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    service0: /service0/**
    service1: /service1/**